# Generated by Django 2.2.14 on 2021-12-22 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_course_question_reply_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.UserModel')),
                ('did', models.IntegerField()),
                ('rank', models.CharField(default='general', max_length=20)),
            ],
            bases=('myapp.usermodel',),
        ),
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.UserModel')),
                ('pid', models.IntegerField()),
            ],
            bases=('myapp.usermodel',),
        ),
        migrations.RenameModel(
            old_name='School',
            new_name='Office',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='school_name',
            new_name='office_name',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='reply',
            name='conNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reply',
            name='proNum',
            field=models.IntegerField(default=0),
        ),
    ]
