# Generated by Django 2.2.14 on 2021-12-28 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=32)),
                ('dName', models.CharField(max_length=32)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(default='x', max_length=50)),
                ('email', models.CharField(default='未注册', max_length=32)),
                ('realName', models.CharField(default='x', max_length=32)),
                ('gender', models.CharField(default='x', max_length=2)),
                ('birthday', models.DateField(null=True)),
                ('idCardNumber', models.CharField(default='x', max_length=18, unique=True)),
                ('phoneNumber', models.CharField(default='x', max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=32)),
                ('dName', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('medical', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=32)),
                ('dName', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(default='x', max_length=50)),
                ('email', models.CharField(default='未注册', max_length=32)),
                ('realName', models.CharField(default='x', max_length=32)),
                ('gender', models.CharField(default='x', max_length=2)),
                ('birthday', models.DateField(null=True)),
                ('idCardNumber', models.CharField(default='x', max_length=18, unique=True)),
                ('phoneNumber', models.CharField(default='x', max_length=11, unique=True)),
                ('college', models.CharField(default='Peking', max_length=32)),
                ('degree', models.CharField(default='Peking', max_length=32)),
                ('is_leader', models.BooleanField()),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Office')),
            ],
        ),
    ]
