# Generated by Django 2.2.14 on 2021-12-28 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_appointment_doctor_medicalrecord_patient_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='office_name',
            new_name='name',
        ),
    ]
