# Generated by Django 2.2.14 on 2021-12-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20211228_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='office',
            field=models.CharField(default='x', max_length=32),
        ),
    ]
