# Generated by Django 2.2.14 on 2021-12-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211228_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='description',
            field=models.CharField(default='有点小病', max_length=32),
        ),
    ]
