# Generated by Django 4.0 on 2021-12-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=32)),
                ('dName', models.CharField(max_length=32)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(default='x', max_length=50)),
                ('email', models.CharField(default='未注册', max_length=32)),
                ('realName', models.CharField(default='x', max_length=32)),
                ('gender', models.CharField(default='x', max_length=2)),
                ('birthday', models.DateField(null=True)),
                ('idCardNumber', models.CharField(default='x', max_length=18, unique=True)),
                ('phoneNumber', models.CharField(default='x', max_length=11, unique=True)),
                ('college', models.CharField(default='Peking', max_length=32)),
                ('degree', models.CharField(default='Peking', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(default='x', max_length=50)),
                ('email', models.CharField(default='未注册', max_length=32)),
                ('realName', models.CharField(default='x', max_length=32)),
                ('gender', models.CharField(default='x', max_length=2)),
                ('birthday', models.DateField(null=True)),
                ('idCardNumber', models.CharField(default='x', max_length=18, unique=True)),
                ('phoneNumber', models.CharField(default='x', max_length=11, unique=True)),
            ],
        ),
    ]
