# Generated by Django 4.0 on 2021-12-23 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='office_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.office'),
        ),
        migrations.AlterField(
            model_name='office',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='leader_username',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
