# Generated by Django 4.0 on 2021-12-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_doctor_office_name_alter_office_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='office_Name',
            new_name='office_name',
        ),
    ]
